# ==============================================================================
# ATLANTIC HERRING
# Evaluate isolation by sea distance
# ==============================================================================
#
# This script evaluates the relationship between pair-wise genetic
# differentiation and the shortest distance by sea among Atlantic herring
# population samples.
#
# Inputs:
#   Herring_FST_pairwise_neutral.csv
#   Herring_FST_pairwise_neutral_long.csv
#   listaSalida.rds
#
# The first two files are generated by:
#   Filter genomic data and estimate pair-wise FST.r
#
# The RDS object contains the previously estimated shortest marine paths.
#
# Analysis:
#   1. Recover the population order used in the pair-wise FST matrix.
#   2. Extract shortest-by-sea paths and calculate their lengths in km.
#   3. Match sea distances and pair-wise FST by population pair.
#   4. Linearize genetic differentiation as FST / (1 - FST).
#   5. Evaluate isolation by distance using a Mantel test with
#      9,999 permutations.
#   6. Save pair-wise data, Mantel statistics, and the relationship plot.
#
# ==============================================================================


# ==============================================================================
# 0. SETUP AND PACKAGES
# ==============================================================================

library(data.table)
library(sf)
library(vegan)


# ==============================================================================
# 1. INPUT FILES
# ==============================================================================

fst_matrix_file <- "Herring_FST_pairwise_neutral.csv"
fst_pairs_file <- "Herring_FST_pairwise_neutral_long.csv"
sea_paths_file <- "listaSalida.rds"

n_permutations <- 9999


# ==============================================================================
# 2. READ PAIR-WISE FST RESULTS
# ==============================================================================

fst_matrix_table <- fread(fst_matrix_file)
fst_pairs <- fread(fst_pairs_file)

population_order <- fst_matrix_table[[1]]
n_populations <- length(population_order)

stopifnot(
  all(c("pop1", "pop2", "FST") %in% names(fst_pairs)),
  n_populations > 1L
)


# ==============================================================================
# 3. EXTRACT SHORTEST DISTANCES BY SEA
# ==============================================================================
#
# The connectivity object follows the structure used in the preceding
# connectivity analysis. Its third element contains the path geometries,
# and the first element of that list contains the shortest marine paths
# used here.
#
# ==============================================================================

connectivity_results <- readRDS(sea_paths_file)

shortest_sea_paths <- sf::st_as_sf(
  connectivity_results[[3]][[1]]
)

sea_distance_km <- as.numeric(
  sf::st_length(shortest_sea_paths)
) / 1000


# ==============================================================================
# 4. ASSIGN POPULATION PAIRS TO SEA DISTANCES
# ==============================================================================
#
# The marine paths were originally stored following the lower triangle of
# the population-by-population matrix. Reconstructing those indices from
# the FST matrix preserves the original population ordering.
#
# ==============================================================================

pair_index <- which(
  lower.tri(matrix(0, n_populations, n_populations)),
  arr.ind = TRUE
)

stopifnot(length(sea_distance_km) == nrow(pair_index))

sea_pairs <- data.table(
  pop1 = population_order[pair_index[, 1]],
  pop2 = population_order[pair_index[, 2]],
  sea_distance_km = sea_distance_km,
  pair_order = seq_len(nrow(pair_index))
)


# ==============================================================================
# 5. MATCH SEA DISTANCES AND FST BY POPULATION PAIR
# ==============================================================================

make_pair_id <- function(pop1, pop2) {
  first <- ifelse(pop1 <= pop2, pop1, pop2)
  second <- ifelse(pop1 <= pop2, pop2, pop1)

  paste(first, second, sep = "__")
}

sea_pairs[, pair_id := make_pair_id(pop1, pop2)]
fst_pairs[, pair_id := make_pair_id(pop1, pop2)]

fst_columns <- c("pair_id", "FST")

if ("n_snps" %in% names(fst_pairs)) {
  fst_columns <- c(fst_columns, "n_snps")
}

comparison_data <- merge(
  sea_pairs,
  fst_pairs[, ..fst_columns],
  by = "pair_id",
  all.x = TRUE,
  sort = FALSE
)

setorder(comparison_data, pair_order)

stopifnot(
  nrow(comparison_data) == nrow(sea_pairs),
  !anyDuplicated(comparison_data$pair_id),
  all(is.finite(comparison_data$sea_distance_km)),
  all(is.finite(comparison_data$FST)),
  all(comparison_data$FST < 1)
)

comparison_data[
  ,
  linearized_fst := FST / (1 - FST)
]


# ==============================================================================
# 6. RECONSTRUCT DISTANCE MATRICES
# ==============================================================================

sea_distance_matrix <- matrix(
  0,
  nrow = n_populations,
  ncol = n_populations,
  dimnames = list(population_order, population_order)
)

linearized_fst_matrix <- matrix(
  0,
  nrow = n_populations,
  ncol = n_populations,
  dimnames = list(population_order, population_order)
)

sea_distance_matrix[lower.tri(sea_distance_matrix)] <-
  comparison_data$sea_distance_km

linearized_fst_matrix[lower.tri(linearized_fst_matrix)] <-
  comparison_data$linearized_fst

sea_distance_matrix <- sea_distance_matrix + t(sea_distance_matrix)

linearized_fst_matrix <-
  linearized_fst_matrix + t(linearized_fst_matrix)

diag(sea_distance_matrix) <- 0
diag(linearized_fst_matrix) <- 0


# ==============================================================================
# 7. MANTEL TEST
# ==============================================================================

mantel_result <- vegan::mantel(
  as.dist(sea_distance_matrix),
  as.dist(linearized_fst_matrix),
  method = "pearson",
  permutations = n_permutations
)

mantel_summary <- data.table(
  statistic = unname(mantel_result$statistic),
  p_value = mantel_result$signif,
  permutations = n_permutations
)


# ==============================================================================
# 8. SAVE ANALYSIS RESULTS
# ==============================================================================

output_pairs <- comparison_data[
  ,
  !c("pair_id", "pair_order"),
  with = FALSE
]

fwrite(
  output_pairs,
  "Herring_FST_sea_distance_pairs.csv"
)

fwrite(
  mantel_summary,
  "Herring_FST_sea_distance_mantel.csv"
)


# ==============================================================================
# 9. SAVE RELATIONSHIP PLOT
# ==============================================================================

png(
  "Herring_FST_sea_distance_relationship.png",
  width = 1800,
  height = 1400,
  res = 200
)

par(
  mar = c(4.5, 5, 1, 1),
  mgp = c(2.5, 0.8, 0)
)

plot(
  output_pairs$sea_distance_km,
  output_pairs$linearized_fst,
  xlab = "Shortest distance by sea (km)",
  ylab = expression(F[ST] / (1 - F[ST])),
  pch = 19,
  las = 1,
  bty = "L"
)

distance_model <- lm(
  linearized_fst ~ sea_distance_km,
  data = output_pairs
)

abline(
  distance_model,
  lwd = 2
)

legend(
  "topleft",
  legend = c(
    paste0(
      "Mantel r = ",
      sprintf("%.3f", mantel_summary$statistic)
    ),
    paste0(
      "P = ",
      sprintf("%.4f", mantel_summary$p_value)
    )
  ),
  bty = "n"
)

dev.off()
