# ==============================================================================
# ATLANTIC HERRING
# Iterative Random Forest resistance-surface analysis
# ==============================================================================
#
# This script uses pair-wise genetic differentiation and oceanographic
# predictors to iteratively estimate a resistance surface connecting Atlantic
# herring sampling localities.
#
# Inputs:
#   capas_new.tif
#   Herring_connectivity_nodes.csv
#   Herring_FST_pairwise_neutral.csv
#
# The FST matrix is generated by:
#   Filter genomic data and estimate pair-wise FST.r
#
# Workflow:
#   1. Prepare oceanographic raster layers and sampling localities.
#   2. Linearize pair-wise FST as FST / (1 - FST).
#   3. Initialize a spatially uniform resistance surface.
#   4. Calculate shortest marine paths among all locality pairs.
#   5. Extract mean oceanographic conditions along each path.
#   6. Fit and tune a Random Forest predicting linearized FST.
#   7. Predict a new resistance surface from the fitted Random Forest.
#   8. Repeat shortest-path estimation and Random Forest fitting for
#      30 iterations.
#   9. Save all resistance surfaces, paths, extracted predictors, and
#      model-performance metrics.
#
# ==============================================================================


# ==============================================================================
# 0. SETUP AND PACKAGES
# ==============================================================================

library(data.table)
library(gdistance)
library(randomForestSRC)
library(raster)
library(terra)


# ==============================================================================
# 1. INPUTS AND PARAMETERS
# ==============================================================================

predictor_file <- "capas_new.tif"
locality_file <- "Herring_connectivity_nodes.csv"
fst_matrix_file <- "Herring_FST_pairwise_neutral.csv"

n_iterations <- 30L


# ==============================================================================
# 2. OCEANOGRAPHIC PREDICTORS
# ==============================================================================

predictor_stack <- raster::stack(predictor_file)
predictor_raster <- terra::rast(predictor_stack)

valid_cells <- which(
  !is.na(raster::calc(predictor_stack, sum)[])
)

prediction_data <- data.frame(
  raster::getValues(predictor_stack)
)


# ==============================================================================
# 3. SAMPLING LOCALITIES
# ==============================================================================

localities <- read.csv(locality_file)

sp::coordinates(localities) <- c("longitude", "latitude")
sp::proj4string(localities) <- raster::crs(predictor_stack)

keep_localities <- which(
  sp::coordinates(localities)[, "longitude"] > -20
)

localities <- localities[keep_localities, ]

missing_cells <- which(
  is.na(
    raster::extract(
      predictor_stack[[1]],
      sp::coordinates(localities)
    )
  )
)

original_coordinates <- sp::coordinates(localities)
adjusted_coordinates <- original_coordinates

for (i in missing_cells) {
  distance_raster <- raster::distanceFromPoints(
    predictor_stack[[1]],
    original_coordinates[i, , drop = FALSE]
  )

  distance_raster[
    is.na(predictor_stack[[1]][])
  ] <- NA

  nearest_cell <- which.min(distance_raster[])

  adjusted_coordinates[i, ] <- raster::xyFromCell(
    predictor_stack[[1]],
    nearest_cell
  )
}

localities <- sp::SpatialPointsDataFrame(
  coords = adjusted_coordinates,
  data = localities@data,
  proj4string = sp::CRS(sp::proj4string(localities))
)


# ==============================================================================
# 4. PAIR-WISE LINEARIZED FST
# ==============================================================================

fst_table <- data.table::fread(fst_matrix_file)

population_names <- fst_table[[1]]
fst_matrix <- as.matrix(fst_table[, -1, with = FALSE])

rownames(fst_matrix) <- population_names
colnames(fst_matrix) <- names(fst_table)[-1]

stopifnot(
  nrow(fst_matrix) == nrow(localities),
  ncol(fst_matrix) == nrow(localities),
  all(is.finite(fst_matrix)),
  all(fst_matrix < 1)
)

linearized_fst_matrix <- fst_matrix / (1 - fst_matrix)
diag(linearized_fst_matrix) <- 0

linearized_fst <- as.dist(linearized_fst_matrix)


# ==============================================================================
# 5. HELPER FUNCTIONS
# ==============================================================================

transition_function <- function(x) {
  1 / mean(x, na.rm = TRUE)
}

calculate_r2 <- function(observed, predicted) {
  1 - sum((observed - predicted)^2) /
    sum((observed - mean(observed))^2)
}

calculate_shortest_paths <- function(resistance_surface, localities) {
  transition_layer <- gdistance::transition(
    x = resistance_surface,
    transitionFunction = transition_function,
    directions = 16
  )

  transition_layer <- gdistance::geoCorrection(
    transition_layer,
    type = "c"
  )

  n_localities <- nrow(localities)

  paths <- gdistance::shortestPath(
    x = transition_layer,
    origin = sp::coordinates(localities)[1, ],
    goal = sp::coordinates(localities)[-1, ],
    output = "SpatialLines"
  )

  if (n_localities > 2L) {
    for (k in 2:(n_localities - 1L)) {
      new_paths <- gdistance::shortestPath(
        x = transition_layer,
        origin = sp::coordinates(localities)[k, ],
        goal = sp::coordinates(localities)[
          (k + 1L):n_localities,
        ],
        output = "SpatialLines"
      )

      paths <- rbind(paths, new_paths)
    }
  }

  sp::proj4string(paths) <- raster::crs(resistance_surface)

  paths
}

extract_path_predictors <- function(
  paths,
  predictor_raster,
  linearized_fst
) {
  paths_terra <- terra::vect(paths)

  path_values <- terra::extract(
    x = predictor_raster,
    y = paths_terra,
    fun = mean,
    na.rm = TRUE,
    touches = TRUE
  )

  path_values$ID <- NULL
  path_values$linearized_fst <- as.vector(linearized_fst)

  path_values
}

fit_random_forest <- function(path_values) {
  tuning <- randomForestSRC::tune.rfsrc(
    linearized_fst ~ .,
    data = path_values,
    trace = FALSE
  )

  model <- randomForestSRC::rfsrc(
    formula = linearized_fst ~ .,
    data = path_values,
    nodesize = tuning$optimal["nodesize"],
    mtry = tuning$optimal["mtry"]
  )

  model
}


# ==============================================================================
# 6. INITIAL RESISTANCE SURFACE
# ==============================================================================

mean_linearized_fst <- mean(
  linearized_fst,
  na.rm = TRUE
)

resistance_surface <- predictor_stack[[1]]
resistance_surface[] <- mean_linearized_fst

resistance_surface[
  is.na(predictor_stack[[1]][])
] <- NA

names(resistance_surface) <- "linearized_fst"


# ==============================================================================
# 7. INITIAL SHORTEST PATHS AND RANDOM FOREST
# ==============================================================================

shortest_paths <- calculate_shortest_paths(
  resistance_surface,
  localities
)

path_values <- extract_path_predictors(
  shortest_paths,
  predictor_raster,
  linearized_fst
)

rf_model <- fit_random_forest(path_values)

rf_prediction <- predict(
  object = rf_model,
  newdata = prediction_data
)

resistance_surface[valid_cells] <- rf_prediction$predicted

r2 <- calculate_r2(
  observed = rf_model$yvar,
  predicted = rf_model$predicted
)

r2_oob <- calculate_r2(
  observed = rf_model$yvar,
  predicted = rf_model$predicted.oob
)


# ==============================================================================
# 8. STORE INITIAL RESULTS
# ==============================================================================

resistance_surfaces <- vector(
  "list",
  n_iterations + 1L
)

path_predictors <- vector(
  "list",
  n_iterations + 1L
)

shortest_path_list <- vector(
  "list",
  n_iterations + 1L
)

model_performance <- vector(
  "list",
  n_iterations + 1L
)

resistance_surfaces[[1]] <- resistance_surface
path_predictors[[1]] <- path_values
shortest_path_list[[1]] <- shortest_paths

model_performance[[1]] <- data.frame(
  iteration = 0L,
  r2 = r2,
  r2_oob = r2_oob
)


# ==============================================================================
# 9. ITERATIVE RANDOM FOREST LOOP
# ==============================================================================

for (iteration in seq_len(n_iterations)) {
  shortest_paths <- calculate_shortest_paths(
    resistance_surface,
    localities
  )

  path_values <- extract_path_predictors(
    shortest_paths,
    predictor_raster,
    linearized_fst
  )

  rf_model <- fit_random_forest(path_values)

  rf_prediction <- predict(
    object = rf_model,
    newdata = prediction_data
  )

  resistance_surface[valid_cells] <- rf_prediction$predicted

  r2 <- calculate_r2(
    observed = rf_model$yvar,
    predicted = rf_model$predicted
  )

  r2_oob <- calculate_r2(
    observed = rf_model$yvar,
    predicted = rf_model$predicted.oob
  )

  result_index <- iteration + 1L

  resistance_surfaces[[result_index]] <- resistance_surface
  path_predictors[[result_index]] <- path_values
  shortest_path_list[[result_index]] <- shortest_paths

  model_performance[[result_index]] <- data.frame(
    iteration = iteration,
    r2 = r2,
    r2_oob = r2_oob
  )
}


# ==============================================================================
# 10. SAVE RESULTS
# ==============================================================================

model_performance <- data.table::rbindlist(
  model_performance
)

analysis_results <- list(
  resistance_surfaces = resistance_surfaces,
  path_predictors = path_predictors,
  shortest_paths = shortest_path_list,
  model_performance = model_performance
)

saveRDS(
  analysis_results,
  "Herring_RF_resistance_iterations.rds"
)

data.table::fwrite(
  model_performance,
  "Herring_RF_resistance_model_performance.csv"
)

raster::writeRaster(
  resistance_surfaces[[length(resistance_surfaces)]],
  filename = "Herring_RF_final_resistance_surface.tif",
  overwrite = TRUE
)
